# Exploration des fichiers `raw`

Ce notebook présente une première exploration des fichiers disponibles dans le répertoire `raw`.

## Objectifs

- Identifier les fichiers présents dans le répertoire `raw`
- Examiner leur structure et leur format
- Vérifier la qualité et la complétude des données
- Repérer les éventuelles valeurs manquantes, doublons ou anomalies
- Préparer les données pour les prochaines étapes d'analyse

## Étapes de l’exploration

1. Inventaire des fichiers disponibles
2. Chargement des données
3. Analyse des dimensions et des types de variables
4. Exploration statistique et visuelle
5. Contrôle de la qualité des données
6. Synthèse des premières observations

Les données originales sont conservées dans leur état brut afin de préserver leur traçabilité.

## Analyse Exploratoire

In [ ]:
import pandas as pd

crop_yield_df = pd.read_csv("../data/raw/crop_yield.csv")

In [31]:
print("5 premiers individus")
display(crop_yield_df.head(5))

print("5 derniers individus")
display(crop_yield_df.head(5))

print(f"Le dataframe crop_yield a {crop_yield_df.shape[0]} lignes et {crop_yield_df.shape[1]} colonnes")

5 premiers individus

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

5 derniers individus

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

Le dataframe crop_yield a 1000000 lignes et 10 colonnes

In [32]:
print("INFORMATIONS GÉNÉRALES")
crop_yield_df.info()

print("\n\nDESCRIPTIONS STATISTIQUES")
crop_yield_df.describe()

INFORMATIONS GÉNÉRALES
<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Region                  1000000 non-null  str
 1   Soil_Type               1000000 non-null  str
 2   Crop                    1000000 non-null  str
 3   Rainfall_mm             1000000 non-null  float64
 4   Temperature_Celsius     1000000 non-null  float64
 5   Fertilizer_Used         1000000 non-null  bool
 6   Irrigation_Used         1000000 non-null  bool
 7   Weather_Condition       1000000 non-null  str
 8   Days_to_Harvest         1000000 non-null  int64
 9   Yield_tons_per_hectare  1000000 non-null  float64
dtypes: bool(2), float64(3), int64(1), str(4)
memory usage: 62.9 MB


DESCRIPTIONS STATISTIQUES

,Rainfall_mm,Temperature_Celsius,Days_to_Harvest,Yield_tons_per_hectare
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,549.981901,27.504965,104.495025,4.649472
std,259.851320,7.220608,25.953412,1.696572
min,100.000896,15.000034,60.000000,-1.147613
25%,324.891090,21.254502,82.000000,3.417637
50%,550.124061,27.507365,104.000000,4.651808
75%,774.738520,33.753267,127.000000,5.879200
max,999.998098,39.999997,149.000000,9.963372

### Définition des colonnes
Nous avons 10 variables regroupées 3 types:

- `Region` définie la région dans laquelle est faite la culture que décrit la ligne. 
Elle est de type `Nominale catégorielle`

- `Soil_Type` décrit le type de sol sur lequel se fait la culture décrite par la ligne. Elle est de type `Nominale catégorielle`

- `Crop` définie l'élémet cultivé sur le sol que décrit la ligne. 
Elle est de type `Nominale catégorielle`

- `Rainfall_mm` est la quantié de précipitation en milimètre sur la culture que décrit la ligne.
Elle est de type `Quantitative continue`

- `Temperature_Celsius` donne la température observée sur la culture qui est décrite par ligne.
Elle est de type `Quantitative continue`

- `Fertilizer_Used` donne l'information de l'usage ou du non usage de fertilisant sur la culture décrite sur la ligne.
Elle est de type `Nominale catégorielle binaire`

- `Irrigation_Used` donne l'information de l'usage ou du non usage d'un système d'irrigation sur la culture décrite sur la ligne.
Elle est de type `Nominale catégorielle binaire`

- `Weather_Condition` fournit l'information sur les conditions météoroliques sur la culture décrite par la ligne.
Elle est de type `Nominale catégorielle`

- `Days_to_Harvest` founit le nombre de jours qui se sont écoulés avant la récolte.
Elle est de type `Quantitative Discrète`

- `Yield_tons_per_hectare` donne le rendemenent en tonne et par heactare pour une culture donnée.
Elle est de type `Quantitative continue`

#### Trouver les valeurs manquantes

In [33]:
crop_yield_df.isna().sum()

Region                    0
Soil_Type                 0
Crop                      0
Rainfall_mm               0
Temperature_Celsius       0
Fertilizer_Used           0
Irrigation_Used           0
Weather_Condition         0
Days_to_Harvest           0
Yield_tons_per_hectare    0
dtype: int64

***Nous pouvons donc conclure que nou n'avons aucune valeur nulle.***

#### Trouver les lignes dupliquées

In [34]:
crop_yield_df.duplicated().sum()

np.int64(0)

***Nous n'avons donc aucune ligne dont la combinaison de colonne est dupliquée***

#### Trouver les différentes catégorie pour chaque variable

Nous avons précédemment vu que nous avions 6 variables , cette observation était uniquement visuelle.
Nous allons maintenant la vérifier par algorithmique.

In [42]:
nbr_cat = 0
for col in crop_yield_df.columns:
    if crop_yield_df[col].dtype == "str" or crop_yield_df[col].dtype == "bool":
        nbr_cat+=1
        print(f"({col}) a {crop_yield_df[col].nunique()} occurences qui sont {crop_yield_df[col].unique()}\npour chaque occurence on a en nombre d'occurence : {crop_yield_df[col].value_counts()}\n\n")

print(f"Nous avons donc {nbr_cat} variables qualitatives catégorielles")

(Region) a 4 occurences qui sont <StringArray>
['West', 'South', 'North', 'East']
Length: 4, dtype: str
pour chaque occurence on a en nombre d'occurence : Region
North    250173
West     250074
South    250054
East     249699
Name: count, dtype: int64


(Soil_Type) a 6 occurences qui sont <StringArray>
['Sandy', 'Clay', 'Loam', 'Silt', 'Peaty', 'Chalky']
Length: 6, dtype: str
pour chaque occurence on a en nombre d'occurence : Soil_Type
Sandy     167119
Loam      166795
Chalky    166779
Silt      166672
Clay      166352
Peaty     166283
Name: count, dtype: int64


(Crop) a 6 occurences qui sont <StringArray>
['Cotton', 'Rice', 'Barley', 'Soybean', 'Wheat', 'Maize']
Length: 6, dtype: str
pour chaque occurence on a en nombre d'occurence : Crop
Maize      166824
Rice       166792
Barley     166777
Wheat      166673
Cotton     166585
Soybean    166349
Name: count, dtype: int64


(Fertilizer_Used) a 2 occurences qui sont [False  True]
pour chaque occurence on a en nombre d'occurence : Fertilizer_Used
False    500060
True     499940
Name: count, dtype: int64


(Irrigation_Used) a 2 occurences qui sont [ True False]
pour chaque occurence on a en nombre d'occurence : Irrigation_Used
False    500509
True     499491
Name: count, dtype: int64


(Weather_Condition) a 3 occurences qui sont <StringArray>
['Cloudy', 'Rainy', 'Sunny']
Length: 3, dtype: str
pour chaque occurence on a en nombre d'occurence : Weather_Condition
Sunny     333790
Rainy     333561
Cloudy    332649
Name: count, dtype: int64


Nous avons donc 6 variables qualitatives catégorielles