# Exploration des fichiers `raw`

Ce notebook présente une première exploration des fichiers disponibles dans le répertoire `raw`.

## Objectifs

- Identifier les fichiers présents dans le répertoire `raw`
- Examiner leur structure et leur format
- Vérifier la qualité et la complétude des données
- Repérer les éventuelles valeurs manquantes, doublons ou anomalies
- Préparer les données pour les prochaines étapes d'analyse

## Étapes de l’exploration

1. Inventaire des fichiers disponibles
2. Chargement des données
3. Analyse des dimensions et des types de variables
4. Exploration statistique et visuelle
5. Contrôle de la qualité des données
6. Synthèse des premières observations

Les données originales sont conservées dans leur état brut afin de préserver leur traçabilité.

## Analyse Exploratoire de `CROP_YIELD`

In [472]:
import pandas as pd

crop_yield_df = pd.read_csv("../data/raw/crop_yield.csv")

In [473]:
print("5 premiers individus")
display(crop_yield_df.head(5))

print("5 derniers individus")
display(crop_yield_df.head(5))

print(f"Le dataframe crop_yield a {crop_yield_df.shape[0]} lignes et {crop_yield_df.shape[1]} colonnes")

5 premiers individus

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

5 derniers individus

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

Le dataframe crop_yield a 1000000 lignes et 10 colonnes

In [474]:
print("INFORMATIONS GÉNÉRALES")
crop_yield_df.info()

print("\n\nDESCRIPTIONS STATISTIQUES")
crop_yield_df.describe()

INFORMATIONS GÉNÉRALES
<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 10 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Region                  1000000 non-null  str
 1   Soil_Type               1000000 non-null  str
 2   Crop                    1000000 non-null  str
 3   Rainfall_mm             1000000 non-null  float64
 4   Temperature_Celsius     1000000 non-null  float64
 5   Fertilizer_Used         1000000 non-null  bool
 6   Irrigation_Used         1000000 non-null  bool
 7   Weather_Condition       1000000 non-null  str
 8   Days_to_Harvest         1000000 non-null  int64
 9   Yield_tons_per_hectare  1000000 non-null  float64
dtypes: bool(2), float64(3), int64(1), str(4)
memory usage: 62.9 MB


DESCRIPTIONS STATISTIQUES

,Rainfall_mm,Temperature_Celsius,Days_to_Harvest,Yield_tons_per_hectare
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,549.981901,27.504965,104.495025,4.649472
std,259.851320,7.220608,25.953412,1.696572
min,100.000896,15.000034,60.000000,-1.147613
25%,324.891090,21.254502,82.000000,3.417637
50%,550.124061,27.507365,104.000000,4.651808
75%,774.738520,33.753267,127.000000,5.879200
max,999.998098,39.999997,149.000000,9.963372

### Définition des colonnes
Nous avons 10 variables regroupées 3 types:

- `Region` définie la région dans laquelle est faite la culture que décrit la ligne. 
Elle est de type `Nominale catégorielle`

- `Soil_Type` décrit le type de sol sur lequel se fait la culture décrite par la ligne. Elle est de type `Nominale catégorielle`

- `Crop` définie l'élémet cultivé sur le sol que décrit la ligne. 
Elle est de type `Nominale catégorielle`

- `Rainfall_mm` est la quantié de précipitation en milimètre sur la culture que décrit la ligne.
Elle est de type `Quantitative continue`

- `Temperature_Celsius` donne la température observée sur la culture qui est décrite par ligne.
Elle est de type `Quantitative continue`

- `Fertilizer_Used` donne l'information de l'usage ou du non usage de fertilisant sur la culture décrite sur la ligne.
Elle est de type `Nominale catégorielle binaire`

- `Irrigation_Used` donne l'information de l'usage ou du non usage d'un système d'irrigation sur la culture décrite sur la ligne.
Elle est de type `Nominale catégorielle binaire`

- `Weather_Condition` fournit l'information sur les conditions météoroliques sur la culture décrite par la ligne.
Elle est de type `Nominale catégorielle`

- `Days_to_Harvest` founit le nombre de jours qui se sont écoulés avant la récolte.
Elle est de type `Quantitative Discrète`

- `Yield_tons_per_hectare` donne le rendemenent en tonne et par heactare pour une culture donnée.
Elle est de type `Quantitative continue`

#### Trouver les valeurs manquantes

In [475]:
crop_yield_df.isna().sum()

Region                    0
Soil_Type                 0
Crop                      0
Rainfall_mm               0
Temperature_Celsius       0
Fertilizer_Used           0
Irrigation_Used           0
Weather_Condition         0
Days_to_Harvest           0
Yield_tons_per_hectare    0
dtype: int64

***Nous pouvons donc conclure que nou n'avons aucune valeur nulle.***

#### Trouver les lignes dupliquées

In [476]:
crop_yield_df.duplicated().sum()

np.int64(0)

***Nous n'avons donc aucune ligne dont la combinaison de colonne est dupliquée***

#### Trouver les différentes catégorie pour chaque variable

Nous avons précédemment vu que nous avions 6 variables , cette observation était uniquement visuelle.
Nous allons maintenant la vérifier par algorithmique.

In [477]:
nbr_cat = 0
for col in crop_yield_df.columns:
    if crop_yield_df[col].dtype == "str" or crop_yield_df[col].dtype == "bool":
        nbr_cat+=1
        print(f"({col}) a {crop_yield_df[col].nunique()} occurences qui sont {crop_yield_df[col].unique()}\npour chaque occurence on a en nombre d'occurence : {crop_yield_df[col].value_counts()}\n\n")

print(f"Nous avons donc {nbr_cat} variables qualitatives catégorielles")

(Region) a 4 occurences qui sont <StringArray>
['West', 'South', 'North', 'East']
Length: 4, dtype: str
pour chaque occurence on a en nombre d'occurence : Region
North    250173
West     250074
South    250054
East     249699
Name: count, dtype: int64


(Soil_Type) a 6 occurences qui sont <StringArray>
['Sandy', 'Clay', 'Loam', 'Silt', 'Peaty', 'Chalky']
Length: 6, dtype: str
pour chaque occurence on a en nombre d'occurence : Soil_Type
Sandy     167119
Loam      166795
Chalky    166779
Silt      166672
Clay      166352
Peaty     166283
Name: count, dtype: int64


(Crop) a 6 occurences qui sont <StringArray>
['Cotton', 'Rice', 'Barley', 'Soybean', 'Wheat', 'Maize']
Length: 6, dtype: str
pour chaque occurence on a en nombre d'occurence : Crop
Maize      166824
Rice       166792
Barley     166777
Wheat      166673
Cotton     166585
Soybean    166349
Name: count, dtype: int64


(Fertilizer_Used) a 2 occurences qui sont [False  True]
pour chaque occurence on a en nombre d'occurence : Fertilizer_Used
False    500060
True     499940
Name: count, dtype: int64


(Irrigation_Used) a 2 occurences qui sont [ True False]
pour chaque occurence on a en nombre d'occurence : Irrigation_Used
False    500509
True     499491
Name: count, dtype: int64


(Weather_Condition) a 3 occurences qui sont <StringArray>
['Cloudy', 'Rainy', 'Sunny']
Length: 3, dtype: str
pour chaque occurence on a en nombre d'occurence : Weather_Condition
Sunny     333790
Rainy     333561
Cloudy    332649
Name: count, dtype: int64


Nous avons donc 6 variables qualitatives catégorielles

## Analyse Exploratoire de `prediction_datasets`

`Yield_df` est un data_set prédictif qui a été utiliser pour valider notre dataset précédent `crop_yield_df`

In [478]:
yield_df = pd.read_csv("../data/raw/prediction_datasets/yield_df.csv")
pesticides_df = pd.read_csv("../data/raw/prediction_datasets/pesticides.csv")
rainfall_df = pd.read_csv("../data/raw/prediction_datasets/rainfall.csv")
temp_df = pd.read_csv("../data/raw/prediction_datasets/temp.csv")
_yield = pd.read_csv("../data/raw/prediction_datasets/yield.csv")

print("yield_df")
display(yield_df.head(5))
display(yield_df.tail(5))

print("\n")

print("pesticides_df")
display(pesticides_df.head(5))
display(pesticides_df.tail(5))

print("\n")

print("rainfall_df")
display(rainfall_df.head(5))
display(rainfall_df.tail(5))

print("\n")

print("temp_df")
display(temp_df.head(5))
display(temp_df.tail(5))

print("\n")

print("_yield")
display(_yield.head(5))
display(_yield.tail(5))

yield_df

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
28237,28237,Zimbabwe,"Rice, paddy",2013,22581,657.0,2550.07,19.76
28238,28238,Zimbabwe,Sorghum,2013,3066,657.0,2550.07,19.76
28239,28239,Zimbabwe,Soybeans,2013,13142,657.0,2550.07,19.76
28240,28240,Zimbabwe,Sweet potatoes,2013,22222,657.0,2550.07,19.76
28241,28241,Zimbabwe,Wheat,2013,22888,657.0,2550.07,19.76

pesticides_df

,Domain,Area,Element,Item,Year,Unit,Value
0,Pesticides Use,Albania,Use,Pesticides (total),1990,tonnes of active ingredients,121.0
1,Pesticides Use,Albania,Use,Pesticides (total),1991,tonnes of active ingredients,121.0
2,Pesticides Use,Albania,Use,Pesticides (total),1992,tonnes of active ingredients,121.0
3,Pesticides Use,Albania,Use,Pesticides (total),1993,tonnes of active ingredients,121.0
4,Pesticides Use,Albania,Use,Pesticides (total),1994,tonnes of active ingredients,201.0

,Domain,Area,Element,Item,Year,Unit,Value
4344,Pesticides Use,Zimbabwe,Use,Pesticides (total),2012,tonnes of active ingredients,3375.53
4345,Pesticides Use,Zimbabwe,Use,Pesticides (total),2013,tonnes of active ingredients,2550.07
4346,Pesticides Use,Zimbabwe,Use,Pesticides (total),2014,tonnes of active ingredients,2185.07
4347,Pesticides Use,Zimbabwe,Use,Pesticides (total),2015,tonnes of active ingredients,2185.07
4348,Pesticides Use,Zimbabwe,Use,Pesticides (total),2016,tonnes of active ingredients,2185.07

rainfall_df

          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

          Area  Year average_rain_fall_mm_per_year
6722  Zimbabwe  2013                           657
6723  Zimbabwe  2014                           657
6724  Zimbabwe  2015                           657
6725  Zimbabwe  2016                           657
6726  Zimbabwe  2017                           657

temp_df

   year        country  avg_temp
0  1849  Côte D'Ivoire     25.58
1  1850  Côte D'Ivoire     25.52
2  1851  Côte D'Ivoire     25.67
3  1852  Côte D'Ivoire       NaN
4  1853  Côte D'Ivoire       NaN

       year country  avg_temp
71306  2009  Mexico     21.76
71307  2010  Mexico     20.90
71308  2011  Mexico     21.55
71309  2012  Mexico     21.52
71310  2013  Mexico     22.19

_yield

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value
0,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1961,1961,hg/ha,14000
1,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1962,1962,hg/ha,14000
2,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1963,1963,hg/ha,14260
3,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1964,1964,hg/ha,14257
4,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1965,1965,hg/ha,14400

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value
56712,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2012,2012,hg/ha,24420
56713,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2013,2013,hg/ha,22888
56714,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2014,2014,hg/ha,21357
56715,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2015,2015,hg/ha,19826
56716,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2016,2016,hg/ha,18294

Exploration de  ***_YIELD***

1 - Trouver les colonnes qui n'ont pas lieu d'être

In [479]:
for col in _yield.columns:
    print(f"Pour {col} on a {_yield[col].nunique()} valeurs différentes")

Pour Domain Code on a 1 valeurs différentes
Pour Domain on a 1 valeurs différentes
Pour Area Code on a 212 valeurs différentes
Pour Area on a 212 valeurs différentes
Pour Element Code on a 1 valeurs différentes
Pour Element on a 1 valeurs différentes
Pour Item Code on a 10 valeurs différentes
Pour Item on a 10 valeurs différentes
Pour Year Code on a 56 valeurs différentes
Pour Year on a 56 valeurs différentes
Pour Unit on a 1 valeurs différentes
Pour Value on a 36815 valeurs différentes

Nous pouvons observer une non variation des colonnes:
- Domain Code
- Domain
- Element Code
- Element
- Unit

Domaine code étant un identifiant du domaine et domain qui est toujours sur la culure.
Element code qui ne change pas vu qu'element est toujours sur rendement.
Nous avons également l'unité de mesure du rendement qui est toujours sur hg/ha(hectogramme par hectare)

**Nous pouvons donc résumer ce _yield comme étant le rendement de différentes cultures par hectgramme par hectare sur différents pays.**

In [480]:
_yield.drop(columns=["Domain Code", "Domain", "Element Code", "Element", "Unit"], inplace=True, errors="ignore")

_yield.rename(columns={
    "Value": "hg/ha_yield"
}, inplace=True)

display(_yield)

       Area Code         Area  Item Code   Item  Year Code  Year  hg/ha_yield
0              2  Afghanistan         56  Maize       1961  1961        14000
1              2  Afghanistan         56  Maize       1962  1962        14000
2              2  Afghanistan         56  Maize       1963  1963        14260
3              2  Afghanistan         56  Maize       1964  1964        14257
4              2  Afghanistan         56  Maize       1965  1965        14400
...          ...          ...        ...    ...        ...   ...          ...
56712        181     Zimbabwe         15  Wheat       2012  2012        24420
56713        181     Zimbabwe         15  Wheat       2013  2013        22888
56714        181     Zimbabwe         15  Wheat       2014  2014        21357
56715        181     Zimbabwe         15  Wheat       2015  2015        19826
56716        181     Zimbabwe         15  Wheat       2016  2016        18294

[56717 rows x 7 columns]

In [481]:
#Verifier s'il y a besoin d'avoir un year code
print(f"Nombre de colonne où Year Code est différent de Year {(_yield["Year Code"] != _yield["Year"]).sum()}")

Nombre de colonne où Year Code est différent de Year 0

In [482]:
#Nous supprimons donc
_yield.drop(columns=["Year Code", "Item Code"], inplace=True, errors="ignore")

In [483]:
display(_yield)

       Area Code         Area   Item  Year  hg/ha_yield
0              2  Afghanistan  Maize  1961        14000
1              2  Afghanistan  Maize  1962        14000
2              2  Afghanistan  Maize  1963        14260
3              2  Afghanistan  Maize  1964        14257
4              2  Afghanistan  Maize  1965        14400
...          ...          ...    ...   ...          ...
56712        181     Zimbabwe  Wheat  2012        24420
56713        181     Zimbabwe  Wheat  2013        22888
56714        181     Zimbabwe  Wheat  2014        21357
56715        181     Zimbabwe  Wheat  2015        19826
56716        181     Zimbabwe  Wheat  2016        18294

[56717 rows x 5 columns]

## Jointures des jeux de données prédictifs

Nous allons fusionner successivement les fichiers suivants :

- **`_yield`** (`yield.csv`) : rendement agricole par pays, culture et année ;
- **`pesticides_df`** (`pesticides.csv`) : utilisation de pesticides par pays et par année ;
- **`rainfall_df`** (`rainfall.csv`) : précipitations moyennes par pays et par année ;
- **`temp_df`** (`temp.csv`) : température moyenne par pays et par année.

Les jointures seront principalement effectuées à partir des variables communes :

- `Area` / `country` pour le pays ;
- `Year` / `year` pour l’année.

L’objectif est d’obtenir un dataframe complet contenant le rendement, la culture, les précipitations, l’utilisation de pesticides et la température. Le dataframe `yield_df`, déjà enrichi par ces informations, pourra servir de référence pour vérifier le résultat des jointures.

`YIELD JOIN PESTICIDES`

In [484]:
display(_yield.head(5))
display(pesticides_df.head(5))

   Area Code         Area   Item  Year  hg/ha_yield
0          2  Afghanistan  Maize  1961        14000
1          2  Afghanistan  Maize  1962        14000
2          2  Afghanistan  Maize  1963        14260
3          2  Afghanistan  Maize  1964        14257
4          2  Afghanistan  Maize  1965        14400

,Domain,Area,Element,Item,Year,Unit,Value
0,Pesticides Use,Albania,Use,Pesticides (total),1990,tonnes of active ingredients,121.0
1,Pesticides Use,Albania,Use,Pesticides (total),1991,tonnes of active ingredients,121.0
2,Pesticides Use,Albania,Use,Pesticides (total),1992,tonnes of active ingredients,121.0
3,Pesticides Use,Albania,Use,Pesticides (total),1993,tonnes of active ingredients,121.0
4,Pesticides Use,Albania,Use,Pesticides (total),1994,tonnes of active ingredients,201.0

In [485]:
merged_df_yp = pd.merge(
    _yield,
    pesticides_df,
    on=["Area", "Year"],
    how="inner"
)
display(merged_df_yp)

,Area Code,Area,Item_x,Year,hg/ha_yield,Domain,Element,Item_y,Unit,Value
0,3,Albania,Maize,1990,36613,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,121.00
1,3,Albania,Maize,1991,29068,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,121.00
2,3,Albania,Maize,1992,24876,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,121.00
3,3,Albania,Maize,1993,24185,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,121.00
4,3,Albania,Maize,1994,25848,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,201.00
...,...,...,...,...,...,...,...,...,...,...
24148,181,Zimbabwe,Wheat,2012,24420,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,3375.53
24149,181,Zimbabwe,Wheat,2013,22888,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,2550.07
24150,181,Zimbabwe,Wheat,2014,21357,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,2185.07
24151,181,Zimbabwe,Wheat,2015,19826,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,2185.07
24152,181,Zimbabwe,Wheat,2016,18294,Pesticides Use,Use,Pesticides (total),tonnes of active ingredients,2185.07

In [486]:
for col in merged_df_yp.columns:
    print(f"Pour {col} on a {merged_df_yp[col].nunique()} valeurs.")

Pour Area Code on a 167 valeurs.
Pour Area on a 167 valeurs.
Pour Item_x on a 10 valeurs.
Pour Year on a 27 valeurs.
Pour hg/ha_yield on a 20126 valeurs.
Pour Domain on a 1 valeurs.
Pour Element on a 1 valeurs.
Pour Item_y on a 1 valeurs.
Pour Unit on a 1 valeurs.
Pour Value on a 2811 valeurs.

In [487]:
#Nous pouvons à présent supprimer les variables unitiles
merged_df_yp.rename(columns={
    "Value": "Pesticides/tonnes of active ingredients"
}, inplace=True)

merged_df_yp.drop(columns=["Domain", "Element", "Item_y", "Unit"], inplace=True, errors="ignore")

display(merged_df_yp.head())

,Area Code,Area,Item_x,Year,hg/ha_yield,Pesticides/tonnes of active ingredients
0,3,Albania,Maize,1990,36613,121.0
1,3,Albania,Maize,1991,29068,121.0
2,3,Albania,Maize,1992,24876,121.0
3,3,Albania,Maize,1993,24185,121.0
4,3,Albania,Maize,1994,25848,201.0

`MERGED_DF_YP JOIN RAINFALL`

In [488]:
display(rainfall_df.head())
rainfall_df.rename(columns={" Area": "Area"}, inplace=True)

          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

In [489]:
merged_df_ypr = pd.merge(
    merged_df_yp,
    rainfall_df,
    on=["Area", "Year"],
    how="inner"
)

display(merged_df_ypr)

,Area Code,Area,Item_x,Year,hg/ha_yield,Pesticides/tonnes of active ingredients,average_rain_fall_mm_per_year
0,3,Albania,Maize,1990,36613,121.00,1485
1,3,Albania,Maize,1991,29068,121.00,1485
2,3,Albania,Maize,1992,24876,121.00,1485
3,3,Albania,Maize,1993,24185,121.00,1485
4,3,Albania,Maize,1994,25848,201.00,1485
...,...,...,...,...,...,...,...
19351,181,Zimbabwe,Wheat,2012,24420,3375.53,657
19352,181,Zimbabwe,Wheat,2013,22888,2550.07,657
19353,181,Zimbabwe,Wheat,2014,21357,2185.07,657
19354,181,Zimbabwe,Wheat,2015,19826,2185.07,657
19355,181,Zimbabwe,Wheat,2016,18294,2185.07,657

`MERGED_DF_YPR JOIN TEMP`

In [490]:
temp_df.rename(columns={"country": "Area", "year": "Year"}, inplace=True)
display(temp_df.head())
display(temp_df.shape)

   Year           Area  avg_temp
0  1849  Côte D'Ivoire     25.58
1  1850  Côte D'Ivoire     25.52
2  1851  Côte D'Ivoire     25.67
3  1852  Côte D'Ivoire       NaN
4  1853  Côte D'Ivoire       NaN

(71311, 3)

In [491]:
merged_df_yprt = pd.merge(
    merged_df_ypr,
    temp_df,
    on=["Area", "Year"],
    how="left"
)

display(merged_df_yprt.head(5))

,Area Code,Area,Item_x,Year,hg/ha_yield,Pesticides/tonnes of active ingredients,average_rain_fall_mm_per_year,avg_temp
0,3,Albania,Maize,1990,36613,121.0,1485,16.37
1,3,Albania,Maize,1991,29068,121.0,1485,15.36
2,3,Albania,Maize,1992,24876,121.0,1485,16.06
3,3,Albania,Maize,1993,24185,121.0,1485,16.05
4,3,Albania,Maize,1994,25848,201.0,1485,16.96

Nous obtenons le dataframe `merged_df_yprt`, issu de la fusion successive des données de rendement, de pesticides, de précipitations et de température. Nous allons maintenant le comparer au dataframe `yield_df`, qui était déjà fusionné, afin de vérifier la cohérence des résultats.

In [492]:
print(f"Nombre de colonnes: merged({merged_df_yprt.shape[1]}), yield_df({yield_df.shape[1]})")
print(f"Nombre de ligne: merged({merged_df_yprt.shape[0]}), yield_df({yield_df.shape[0]})")
print(f"Nombre de ligne dupliquées: merged({merged_df_yprt.duplicated().sum()}), yield_df({yield_df.duplicated().sum()})")

Nombre de colonnes: merged(8), yield_df(8)
Nombre de ligne: merged(34468), yield_df(28242)
Nombre de ligne dupliquées: merged(2310), yield_df(0)

In [493]:
merged_df_yprt.drop_duplicates(inplace=True)

print(f"Nombre de ligne: merged({merged_df_yprt.shape[0]}), yield_df({yield_df.shape[0]})")
print(f"Nombre de ligne dupliquées: merged({merged_df_yprt.duplicated().sum()}), yield_df({yield_df.duplicated().sum()})")

Nombre de ligne: merged(32158), yield_df(28242)
Nombre de ligne dupliquées: merged(0), yield_df(0)

In [494]:
print("merged_df_yprt")
display(merged_df_yprt.isna().sum())
print("\n\nyield_df")
display(yield_df.isna().sum())

merged_df_yprt

Area Code                                     0
Area                                          0
Item_x                                        0
Year                                          0
hg/ha_yield                                   0
Pesticides/tonnes of active ingredients       0
average_rain_fall_mm_per_year               401
avg_temp                                   6220
dtype: int64

yield_df

Unnamed: 0                       0
Area                             0
Item                             0
Year                             0
hg/ha_yield                      0
average_rain_fall_mm_per_year    0
pesticides_tonnes                0
avg_temp                         0
dtype: int64

### Bilan de l'exploration croisée et choix du dataset

Afin de comprendre l'origine et la structure du dataset `yield_df.csv` fourni, j'ai procédé à la reconstruction manuelle de ce fichier à partir des données brutes de la FAO (`yield.csv`, `pesticides.csv`, `rainfall.csv`, `temp.csv`). 

**Observations :**
- La fusion manuelle de ces 4 fichiers génère un dataset de **32 158 lignes**, comportant de nombreuses valeurs manquantes (notamment sur la température et la pluviométrie).
- Le dataset `yield_df.csv` fourni initialement contient **28 242 lignes** avec **0 valeur manquante**.

**Conclusion :**
L'écart de volumétrie et l'absence de valeurs nulles dans le fichier pré-existant indiquent que son auteur a appliqué un nettoyage strict, vraisemblablement en supprimant les lignes incomplètes (`.dropna()`) ou en réalisant des jointures purement internes (`inner joins`) excluant les zones/années sans données météorologiques.

Si recréer le dataset manuellement était un exercice fondamental pour en auditer la qualité et comprendre le lignage de la donnée (Data Lineage), tenter de reproduire la combinaison exacte des filtres de l'auteur original s'avère coûteux en temps pour un bénéfice marginal. 

**Décision technique :**
Dans une optique de pragmatisme et de fiabilité pour la suite de notre pipeline Machine Learning, nous décidons de **capitaliser sur le dataset `yield_df.csv` pré-nettoyé**. Cela nous garantit une base saine et sans valeurs aberrantes pour attaquer la fusion complexe avec notre fichier d'un million de lignes (`crop_yield.csv`).

# Etudes de CROP_YIELD_DF et de YIELD_DF

In [495]:
display(crop_yield_df.head(5))
display(yield_df.head(5))

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

,Unnamed: 0,Area,Item,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

Pour fusionner les deux datasets nous avons besoins d'une colonne commune.
Dans `Crop_yield_df` nous avons **region** qui pourrai nous faire comprendre la situation géographique, l'homologue de ce dernier dans yield_df est "Area". Nous ne pouvons cependant faire une jointure en se basant sur ces deux variables.
Les seuls colonnes le permettant sont: **Crop** dans `Crop_yield_df`et **Item** dans `yield_df`. Nous allons donc renommer *Item* en *Crop* ce qui est plus parlant et logique pour la suite et faire une **Aggrégation afin d'obtenir les différentes mesures en moyenne**.

In [496]:
#Renommer la colonne Item
yield_df.rename(columns={"Item": "Crop"}, inplace=True)

#Aggréger les données 
yield_df_agg = yield_df.groupby("Crop").agg({
    "hg/ha_yield": "mean", #Rendement moyen,
    "average_rain_fall_mm_per_year": "mean", #Pluviométrie moyenne
    "pesticides_tonnes": "mean", #Utilisation moyenne de pesticide,
    "avg_temp": "mean", #Température moyenne.
}).reset_index()

print("yield_df_agg")
display(yield_df.head())

crop_df = pd.merge(
    crop_yield_df,
    yield_df_agg,
    on="Crop",
    how="inner"
)

print("crop_df")
display(crop_df.head())

yield_df_agg

,Unnamed: 0,Area,Crop,Year,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,0,Albania,Maize,1990,36613,1485.0,121.0,16.37
1,1,Albania,Potatoes,1990,66667,1485.0,121.0,16.37
2,2,Albania,"Rice, paddy",1990,23333,1485.0,121.0,16.37
3,3,Albania,Sorghum,1990,12500,1485.0,121.0,16.37
4,4,Albania,Soybeans,1990,7000,1485.0,121.0,16.37

crop_df

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251,30116.267825,957.285974,35453.21293,18.131623
1,West,Clay,Wheat,357.902357,31.593431,False,False,Rainy,90,2.652392,30116.267825,957.285974,35453.21293,18.131623
2,North,Silt,Wheat,181.587861,26.752729,True,False,Sunny,127,2.943716,30116.267825,957.285974,35453.21293,18.131623
3,West,Sandy,Wheat,395.048968,17.646199,False,True,Rainy,140,3.707293,30116.267825,957.285974,35453.21293,18.131623
4,North,Peaty,Wheat,385.135314,21.656192,False,False,Sunny,73,2.564442,30116.267825,957.285974,35453.21293,18.131623

In [497]:
print(f"Nombre de ligne de CROP_YIELD_DF {crop_yield_df.shape[0]}")
print(f"Nombre de ligne de CROP_DF {crop_df.shape[0]}")

Nombre de ligne de CROP_YIELD_DF 1000000
Nombre de ligne de CROP_DF 333497

In [498]:
crop_df = pd.merge(
    crop_yield_df,
    yield_df_agg,
    on="Crop",
    how="left"
)

print("crop_df")
display(crop_df.head())

print(f"Nombre de ligne de CROP_YIELD_DF {crop_yield_df.shape[0]}")
print(f"Nombre de ligne de CROP_DF {crop_df.shape[0]}")

crop_df

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816,NaN,NaN,NaN,NaN
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341,NaN,NaN,NaN,NaN
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443,NaN,NaN,NaN,NaN
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573,NaN,NaN,NaN,NaN
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251,30116.267825,957.285974,35453.21293,18.131623

Nombre de ligne de CROP_YIELD_DF 1000000
Nombre de ligne de CROP_DF 1000000

### Comparaison des jointures

La jointure entre `crop_yield_df` et `yield_df_agg` sur la colonne `Crop` produit :

- **333 497 lignes** avec une jointure `inner` ;
- **1 000 000 lignes** avec une jointure `left`, en conservant toutes les lignes de `crop_yield_df`.

La jointure `left` permet donc de ne perdre aucune observation du dataset principal `crop_yield_df`.

Nous avons donc soit 70% de lignes perdues en *inner join* soit 70% de valeurs nulles en *left join*.
Nous allons donc auditer nos catégories.

In [499]:
crop_yield_items = set(crop_yield_df["Crop"].unique())
yield_items = set(yield_df["Crop"].unique())

print(f"Les éléments figurant dans crop_yield et ne figurant pas dans yield {crop_yield_items-yield_items}")
print(f"Les éléments figurant dans yield et ne figurant pas dans crop_yield {yield_items - crop_yield_items}")

Les éléments figurant dans crop_yield et ne figurant pas dans yield {'Soybean', 'Rice', 'Cotton', 'Barley'}
Les éléments figurant dans yield et ne figurant pas dans crop_yield {'Plantains and others', 'Yams', 'Soybeans', 'Sweet potatoes', 'Potatoes', 'Cassava', 'Sorghum', 'Rice, paddy'}

Lors de l'analyse exploratoire croisée des jeux de données `crop_yield.csv` et `yield_df.csv`, nous avons identifié des divergences dans la dénomination de certaines cultures identiques. 

Ces différences de nomenclature s'expliquent par les sources des données (notamment la nomenclature spécifique de la FAO pour `yield_df.csv`). Afin de pouvoir fusionner correctement ces deux sources sans générer de valeurs manquantes (`NaN`) inutiles, nous devons standardiser les noms.

**Incohérences identifiées :**
*   **Le Soja :** Nommé `Soybean` (singulier) dans le jeu de données agronomique, mais `Soybeans` (pluriel) dans l'historique de rendement.
*   **Le Riz :** Nommé `Rice` dans le premier, et `Rice, paddy` (riz brut) dans le second.

**Stratégie de résolution :**
Nous appliquons un dictionnaire de correspondance (Mapping) pour aligner les valeurs de `yield_df.csv` sur le standard de `crop_yield.csv`. Cette étape est un prérequis indispensable avant de procéder à une jointure

In [500]:
mapping_crop = {
    "Soybeans": "Soybean",
    "Rice, paddy": "Rice"
}

#faire le remplacement
yield_df_agg["Crop"] = yield_df_agg["Crop"].replace(mapping_crop)


crop_df = pd.merge(
    crop_yield_df,
    yield_df_agg,
    on="Crop",
    how="inner"
)

print("crop_df")
display(crop_df.head())

print(f"Nombre de ligne de CROP_YIELD_DF {crop_yield_df.shape[0]}")
print(f"Nombre de ligne de CROP_DF {crop_df.shape[0]}")

crop_df

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare,hg/ha_yield,average_rain_fall_mm_per_year,pesticides_tonnes,avg_temp
0,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341,40730.434770,1186.672963,36942.215995,21.265378
1,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573,16731.092771,1110.774744,40752.554896,19.660279
2,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251,30116.267825,957.285974,35453.212930,18.131623
3,South,Silt,Soybean,797.471182,37.704974,False,True,Rainy,74,5.898416,16731.092771,1110.774744,40752.554896,19.660279
4,West,Clay,Wheat,357.902357,31.593431,False,False,Rainy,90,2.652392,30116.267825,957.285974,35453.212930,18.131623

Nombre de ligne de CROP_YIELD_DF 1000000
Nombre de ligne de CROP_DF 666638

### Stratégie de Fusion : Préservation des données via Left Join

Après la phase de mapping, l'objectif est d'enrichir les données agronomiques détaillées de `crop_yield.csv` avec les moyennes historiques (climat et pesticides) issues de `yield_df.csv`.

**Le problème identifié :**
Les cultures d'orge (`Barley`) et de coton (`Cotton`), présentes dans `crop_yield.csv`, n'ont aucun équivalent dans les données historiques de la FAO (`yield_df.csv`). 

**Choix technique (Left Join vs Inner Join) :**
*   Une jointure stricte (`Inner Join`) nous aurait fait perdre **333 362 observations**, soit environ 33% de notre jeu de données, éliminant totalement l'orge et le coton de notre périmètre d'analyse.
*   **Décision :** Nous optons pour une jointure à gauche (`Left Join`) en utilisant `crop_yield.csv` comme table de référence. 

**Conséquences et prochaines étapes :**
Cette stratégie permet de conserver nos 1 000 000 d'observations intactes. Cependant, elle génère des valeurs manquantes (`NaN`) sur les variables historiques pour le coton et l'orge (environ 666 638 lignes ont trouvé une correspondance). Nous traiterons ces valeurs manquantes dans la prochaine phase via une stratégie d'imputation adaptée, afin de ne pas réduire le catalogue de cultures recommandables par notre API.

Pour éviter une colinéarité accrue sur les variables nous garderons que les colonnes `Crop` `Pesticides tonnes` du dataset aggrégé. Choix qui réduira nos NaN que nous remplirons par des 0 pour dire qu'on les a pas.

In [508]:
crop_df = pd.merge(
    crop_yield_df,
    yield_df_agg[["Crop", "pesticides_tonnes"]],
    on="Crop",
    how="left"
)

crop_df.rename(columns={"pesticides_tonnes": "pesticides_tonnes_mean"}, inplace=True)

print("crop_df")
display(crop_df.head())

print(f"Nombre de ligne de CROP_YIELD_DF {crop_yield_df.shape[0]}")
print(f"Nombre de ligne de CROP_DF {crop_df.shape[0]}\n\n")

print("Nombre de valeurs nulles")
display(crop_df.isna().sum())

crop_df["pesticides_tonnes_mean"] = crop_df["pesticides_tonnes_mean"].fillna(0)
display(crop_df.head())



#Enregistrer le dataset nettoyé
crop_df.to_csv("../data/processed/final_dataset.csv", index=False)

crop_df

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare,pesticides_tonnes_mean
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816,NaN
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341,36942.215995
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443,NaN
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573,40752.554896
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251,35453.212930

Nombre de ligne de CROP_YIELD_DF 1000000
Nombre de ligne de CROP_DF 1000000


Nombre de valeurs nulles

Region                         0
Soil_Type                      0
Crop                           0
Rainfall_mm                    0
Temperature_Celsius            0
Fertilizer_Used                0
Irrigation_Used                0
Weather_Condition              0
Days_to_Harvest                0
Yield_tons_per_hectare         0
pesticides_tonnes_mean    333362
dtype: int64

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare,pesticides_tonnes_mean
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816,0.000000
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341,36942.215995
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443,0.000000
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573,40752.554896
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251,35453.212930